### ISSUE TITLE
Search not finding TE section from Manual 1

### ISSUE THREAD

**Issue by blalond** [maths22/ftc-manual-browser#9]
Hello. Thanks for this great resource!
I found that the search is not returning results for searches for strings under Game Manual 1 section "7.4 Team Scoring Element" i.e. search for TE05 and you get forum results but not Game Manual results.

**Comment by maths22** [comment]
Thanks, I'll fix that.  I think the issue is that the section heading doesn't include the word "Definition", but I'll get that fixed

**Comment by blalond** [comment]
Thanks! I see that it worked.
